dockerfile# Use official Python base image
FROM python:3.11-slim


WORKDIR /Hussar_API_v1


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . .

COPY cert.pem key.pem ./

EXPOSE 5443

# Run the app with gunicorn (production-ready server)
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]