
FROM python:3.11-slim


WORKDIR /Hussar_API_v1


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . .

COPY cert.pem key.pem ./

EXPOSE 5443

CMD ["gunicorn", "--bind", "0.0.0.0:5443", "--certfile=cert.pem", "--keyfile=key.pem", "app:app"]